# Generated by Django 5.1.4 on 2025-01-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="horas_por_dia",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="alocacao",
            name="horas",
            field=models.PositiveIntegerField(default=8),
        ),
    ]
