# Generated by Django 5.1.4 on 2025-01-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_projeto_horas_por_dia_alter_alocacao_horas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="horas_por_dia",
        ),
    ]
